### ISSUE TITLE
Updates not found based on new release

### ISSUE THREAD

**Issue by actuallymentor** [electron/update.electronjs.org#125]
For [these releases](https://github.com/actuallymentor/battery/releases), the [update url](https://update.electronjs.org/actuallymentor/battery/darwin-arm64/1.0.9) returns `No updates found (needs asset matching *{mac,darwin,osx}*.zip in public repository)`.

However I:

- [x] have a public repo
- [x] publish builds using Github releases
- [x] have code-signed builds
- [x] have a `*-arm64-mac.zip` file attached to the release

What could lead to this not working?

**Comment by erickzhao** [comment]
Transferring this issue over to the right repo! This seems to be related to the backend endpoint rather than the client-side code.

**Comment by erickzhao** [comment]
It looks like that error message is bad/inaccurate. The regex specified is wrong. We actually use the following regex to find macOS arm64 assets:

https://github.com/electron/update.electronjs.org/blob/7bd992d076752b1eb01898232398b39069798fe5/index.js#L269-L271

I think to fix your issue, the arch part should go _after_ the OS part like so:

```
https://github.com/actuallymentor/battery/releases/download/v1.0.9/battery-1.0.9-mac-arm64.zip
```

**Comment by fttx** [comment]
Hello, I've a similar issue, I'm using electron-builder to generate github releases, and it outputs files with this name:

`myapp-1.0.0-arm64-mac.zip`

while the service is expecting this format:

battery-1.2.2-mac-arm64.dmg
[battery-1.2.2-mac-arm64.dmg](https://github.com/actuallymentor/battery/releases/download/v1.2.2/battery-1.2.2-mac-arm64.dmg)
