### ISSUE TITLE
Windows: Support 64 and 32 bit

### ISSUE THREAD

**Issue by felixrieseberg** [electron/update.electronjs.org#63]
I'm wondering if this service supports producing both x64 and ia32 versions of apps. I don't want to exclude users on weaker Windows machines, but I also don't want to punish those with beefy machines.

We could teach the service to detect `ia32` and `x64` identifiers - and `update-electron-app` to pass on what architecture they're running on right now.

**Comment by zeke** [comment]
cc @juliangruber 

I think this may also have been a requirement for Atom? cc @daviwil

**Comment by daviwil** [comment]
Yep, Atom serves both x64 and ia32 Windows builds via our custom update service, so we'd need a similar capability here.

**Comment by daviwil** [comment]
I just realized that it'd probably be helpful for me to write out exactly how our updates work so that our requirements are clearer. Will take a stab at that this weekend ☺

**Comment by juliangruber** [comment]
If we can solve this without adding a config file than we should be able to roll it out swiftly. It looks like luckily we can do this, and without a breaking change.

https://github.com/electron/update.electronjs.org/blob/d4c005f3a5a1fda35ceda27e121803e138cfb9f0/index.js#L213

Any `.exe` is currently picked up as a `win32` release (`win32-x64` effectively). hyper is one of the apps not mentioning the arch in their windows release assets: https://github.com/zeit/hyper/releases/tag/2.1.0-canary.2.

This would mean that any `.exe` would still need to be detected as `win32-x64`, and the new windows asset detection rules would then be:

- `*win32-x64*` -> `win32-x64`
- `*win32-ia32*` -> `win32-ia32`
- `*.exe` -> `win32-x64`

Does this sound good to everyone?

**Comment by juliangruber** [comment]
this has been deployed 🍾 time to update https://github.com/electron/update-electron-app

**Comment by zeke** [comment]
🍻
